version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-updates:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
    assignees:
      - "viamin"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "viamin"
